# Generated by Django 4.2 on 2023-05-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rufus_app', '0005_remove_dish_menus_dish_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='name',
        ),
    ]
