# Generated by Django 4.2 on 2023-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufus_app', '0006_remove_dish_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishitem',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_items',
            field=models.ManyToManyField(related_name='dishes', to='rufus_app.dishitem'),
        ),
    ]
