# Generated by Django 4.2 on 2023-05-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufus_app', '0007_remove_dishitem_dishes_dish_dish_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_items',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='rufus_app.dishitem'),
        ),
    ]
