# Generated by Django 4.2 on 2023-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufus_app', '0008_alter_dish_dish_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishitem',
            name='pictogram_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
