# Generated by Django 4.2 on 2023-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rufus_app', '0010_alter_dishitem_pictogram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dishitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
